# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajilo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_hostel',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
