# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajilo', '0005_auto_20170808_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_hostel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='all_hostel',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
