# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajilo', '0006_auto_20170808_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_hostel',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
